/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2022-07-15 04:26:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.VerifyRequestModel;
import org.apache.catalina.mbeans.UserMBean;
import com.model.ShareRequestDocModel;
import com.model.DocumentModel;
import java.util.List;
import com.model.UserModel;
import com.database.ConnectionManager;

public final class propertyverification_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.VerifyRequestModel");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.DocumentModel");
    _jspx_imports_classes.add("org.apache.catalina.mbeans.UserMBean");
    _jspx_imports_classes.add("com.model.UserModel");
    _jspx_imports_classes.add("com.database.ConnectionManager");
    _jspx_imports_classes.add("com.model.ShareRequestDocModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=utf-8 />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/inc.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"main-panel\">\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"page-title\">Registrar Property Verification Panel</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"card-title\">Pending For Verification</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"myInput\" class=\"form-control w-50\" type=\"text\" placeholder=\"Search..\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t style=\"margin-bottom: 1px; margin-top: 3px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"table-full-width\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Sr.No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Property</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Owner</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Property ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Survey No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Area(Sq.Ft.)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Reg.Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Sign/Reject</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"myTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													List list = ConnectionManager.getPendingDocList();
												int i = 0;
													for (i = 0; i < list.size(); i++) {
														VerifyRequestModel dm = (VerifyRequestModel) list.get(i);
														UserModel um = ConnectionManager.getUserNameFromUid(dm.getUserid());
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i+1 );
      out.write(".</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"cursor: pointer\" onclick=\"javascript:fnViewDoc('");
      out.print(dm.getDid());
      out.write("')\">");
      out.print(dm.getProptype());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(um.getFname());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(dm.getPropid());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(dm.getSurveyno());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(dm.getProparea());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
 String da = dm.getCurrenttimedate();
													  da = da.substring(0, da.indexOf(' '));
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(da);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(dm.getStatus());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(dm.getAddr());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal fade\" id=\"modalUpdateDoc");
      out.print(dm.getDid());
      out.write("\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modalUpdatePro\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-content\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-header bg-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"la la-frown-o\"></i> PDFViewer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body text-center\"  heigth=\"500px\"width=\"500px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<embed id=\"pdfset\" style=\"display:block\" target=\"new\" src=\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=viewShareFile2&sid=");
      out.print(dm.getDid());
      out.write("\"type=\"application/pdf\" height=\"400px\" width=\" 480px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t\tSign/Reject Here -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"td-actions text-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tSign/Reject\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-labelledby=\"dropdownMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdownload preview Email a copy -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn dropdown-item\" onclick=\"javascript:fnSignFile('");
      out.print(dm.getDid());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ConnectionManager.getFilenameFromdid(dm.getDid()));
      out.write("');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"la la-check text-success\" style=\"font-size: 15px;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tSign</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn dropdown-item\" onclick=\"javascript:fnRejectFile('");
      out.print(dm.getDid());
      out.write("');\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"la la-close text-danger\" style=\"font-size: 15px;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tReject</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"td-actions text-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"la  la-arrow-circle-down\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 20px;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\taria-labelledby=\"dropdownMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdownload preview Email a copy -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" target=\"_blank\" -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"la la-cloud-download\" style=\"font-size: 15px;\"></i> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tDownload</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"javascript:fnViewDoc('");
      out.print(dm.getDid() );
      out.write("')\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"la la-folder-open-o\" style=\"font-size: 15px;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tPreview</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal fade\" id=\"modalUpdate1\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"dialog\" aria-labelledby=\"modalUpdatePro\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-header bg-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"la la-frown-o\"></i> Request to Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form class=\"navbar-left navbar-form nav-search mr-md-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"requestsign\" action=\"javascript:fnRequestSign();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \" id=\"docname\">Document Name :\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Need to Sign before requesting?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> <i class=\"la la-frown-o\"></i>All sign by<input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"date\" name=\"cdate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"docid\" name=\"docid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"successInput\" name=\"uname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Email ID or Mobile Number\"> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"successInput\" name=\"msg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Add a message\" style=\"width: 100%\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> <input type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"Submit\" style=\"width: 50%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t<p>Currently the pro version of the <b>Ready Dashboard</b> Bootstrap is in progress development</p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t<p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t<b>We'll let you know when it's done</b></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal fade\" id=\"modalUpdatesignin\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"dialog\" aria-labelledby=\"modalUpdatePro\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-header bg-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"la la-frown-o\"></i> Request to Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form class=\"navbar-left navbar-form nav-search mr-md-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=signFile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \" id=\"signdocname\">Document Name :\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Need to Sign before digital sign?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> <input type=\"text\" id=\"successInput\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Email Certificate Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"signdocid\" name=\"signdocid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"btn btn-default\" accept=\"application/p12\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"file\" name=\"file\" class=\"form-control\"><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-header \" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> <input type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"Sign Document\" style=\"width: 50%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("  $(\"#myInput\").on(\"keyup\", function() {\r\n");
      out.write("    var value = $(this).val().toLowerCase();\r\n");
      out.write("    $(\"#myTable tr\").filter(function() {\r\n");
      out.write("      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footerinc.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fnShowValue(a,b){\t\r\n");
      out.write("// \talert(b);\r\n");
      out.write("\tdocument.getElementById('docid').value=a;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById('docname').innerHTML='Document Name : '+b;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#modalUpdate1\").modal(\"show\");\r\n");
      out.write("}\r\n");
      out.write("function fnSignFile(a,b){\t\r\n");
      out.write("// \talert(b);\r\n");
      out.write("\tdocument.getElementById('signdocid').value=a;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById('signdocname').innerHTML='Document Name : '+b;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#modalUpdatesignin\").modal(\"show\");\r\n");
      out.write("}\r\n");
      out.write("//function fnViewDoc(a){\t\r\n");
      out.write("// \talert(b);\r\n");
      out.write("// \tdocument.getElementById('docid').value=a;\r\n");
      out.write("\t\r\n");
      out.write("// \tdocument.getElementById('docname').innerHTML='Document Name : '+b;\r\n");
      out.write("//\t$(\"#\"+a).modal(\"show\");\r\n");
      out.write("//}\r\n");
      out.write("\r\n");
      out.write("function fnRejectFile(did){\r\n");
      out.write("\t\r\n");
      out.write("\tif(confirm('Are You Sure Want to Reject This Property?')){\r\n");
      out.write("\t\tvar str = \"did=\" + did;\r\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=rejectFile\",\r\n");
      out.write("\t\t\tstr, function(data) {\r\n");
      out.write("\t\t\t\tdata = $.trim(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\talert(\"Property Rejected Successfully!\");\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"");
      out.print(request.getContextPath());
      out.write("/pages/propertyverification.jsp\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"Error Rejecting Property\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fnViewDoc(did){\t\r\n");
      out.write("// \talert(b);\r\n");
      out.write("// \tdocument.getElementById('docid').value=a;\r\n");
      out.write("\t\r\n");
      out.write("// \tdocument.getElementById('docname').innerHTML='Document Name : '+b;\r\n");
      out.write("\t//$(\"#\"+a).modal(\"show\");\r\n");
      out.write("\t\ts='';\r\n");
      out.write("params = 'scrollbars=no,resizable=no,status=no,location=no,toolbar=no,menubar=no,width=1000,height=700';\r\n");
      out.write("s2=\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=viewSharedFile&fid=\"+did+\"&inline=1\";\r\n");
      out.write("\twindow.open(s2, 'My PDF', params);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function fnRequestSign(){\t\r\n");
      out.write("var str = $(\"#requestsign\" ).serialize();\r\n");
      out.write("\r\n");
      out.write("$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=requestsign\",\r\n");
      out.write("\t\tstr, function(data) {\r\n");
      out.write("\t\t\tdata = $.trim(data);\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\twindow.location.href=\"");
      out.print(request.getContextPath());
      out.write("/pages/dashboard.jsp\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#myform')[0].reset();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
